/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'boost.browser-logs': [];
        home: [];
        login: [];
        'login.store': [];
        register: [];
        'register.store': [];
        'verification.notification': [];
        'verification.verify': [
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [];
        logout: [];
        dashboard: [];
        workers: [];
        'workers.create': [];
        'workers.store': [];
        'workers.show': [
            {
                name: 'worker';
                required: true;
                binding: 'id';
            },
        ];
        'workers.update': [
            {
                name: 'worker';
                required: true;
                binding: 'id';
            },
        ];
        'workers.role': [
            {
                name: 'worker';
                required: true;
                binding: 'id';
            },
        ];
        'workers.destroy': [
            {
                name: 'worker';
                required: true;
                binding: 'id';
            },
        ];
        services: [];
        'services.create': [];
        'services.store': [];
        'services.show': [
            {
                name: 'service';
                required: true;
                binding: 'slug';
            },
        ];
        'services.edit': [
            {
                name: 'service';
                required: true;
            },
        ];
        'services.update': [
            {
                name: 'service';
                required: true;
                binding: 'slug';
            },
        ];
        'services.active': [
            {
                name: 'service';
                required: true;
                binding: 'slug';
            },
        ];
        'services.destroy': [
            {
                name: 'service';
                required: true;
                binding: 'slug';
            },
        ];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
        'storage.local.upload': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
